services:
  wordle_backend:
    container_name: wordle_backend
    build:
      context: ./backend
    env_file:
      - .env
    volumes:
      - ${PWD}/backend/database.sqlite3:/app/database.sqlite3
    expose:
      - "${VITE__RUN__SERVER_PORT}"
    healthcheck:
      test: curl --fail http://localhost:${VITE__RUN__SERVER_PORT}/api/v1/health
      start_period: 5s
      interval: 600s
      timeout: 5s
      retries: 3
    restart: always
    networks:
      - internal

  wordle_frontend_nginx:
    container_name: wordle_frontend_nginx
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE__DEBUG: ${VITE__DEBUG}
        VITE__MAIN_API_PREFIX: ${VITE__MAIN_API_PREFIX}
        VITE__SECONDARY_API_PREFIX: ${VITE__SECONDARY_API_PREFIX}
        VITE__GAME_THRESHOLD_HOURS: ${VITE__GAME_THRESHOLD_HOURS}
        VITE__DAILY_UPDATE_TIME_UTC: ${VITE__DAILY_UPDATE_TIME_UTC}
        VITE__CLEANUP_INTERVAL_DAYS: ${VITE__CLEANUP_INTERVAL_DAYS}
    env_file:
      - .env
    volumes:
      - ./nginx/logs:/var/log/nginx               # Logs for fail2ban
      - ./certbot/www:/var/www/certbot            # Certbot HTTP challenge
      - ./certbot/conf:/etc/letsencrypt           # SSL certificates
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordle_backend
      - certbot
    restart: always
    networks:
      - internal
    
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      /bin/sh -c '
        trap "exit" TERM INT;
        while :; do
          certbot renew --webroot -w /var/www/certbot ;
          sleep 12h &
          wait $!;
        done
      '
      
  nginx-reloader:
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      /bin/sh -c '
        trap "exit" TERM INT;
        while :; do
          docker kill -s HUP wordle_frontend_nginx || true;
          sleep 12h &
          wait $!;
        done
      '

      
networks:
  internal:
    driver: bridge
